### ISSUE TITLE
crash during launch, metamachine slot already occupied

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [Technus/TecTech#10]
using latest build

https://pastebin.com/jkv4XXpB

**Comment by Technus** [comment]
http://jenkins.usrv.eu:8080/job/Tec%20Tech/8/artifact/build/libs/TecTech-1.7.10-3.6.5.jar
try this build and send logs

**Comment by bHXDgiuMa5yLHyC8** [comment]
this is the crash report with the same pack (has a modified gregtech jar):

https://pastebin.com/CsHSciG8

this is the crash report with just regular 32pre4 and dependencies:

https://pastebin.com/azFAPU40

**Comment by Technus** [comment]
what is  the modified gregtech jar anyway? Since it uses my wetTransformer code that i moved to GTNH coremod. Where is that distributed, who made it?

the second one should be solved

**Comment by bHXDgiuMa5yLHyC8** [comment]
It works with the vanilla 32pre4 .jar now, thanks. (modified one still crashes)

This is the other .jar I was testing: https://vk.com/wall-110226090_1181

**Comment by draknyte1** [comment]
All forms of GT must follow these allocations for TileEntities. 
https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/api/GregTech_API.java#68

There is a reason these are allocated, so conflicts do not occur between forks and addons.

**Comment by Technus** [comment]
the thing is that some one put GTNH tiles into gregtech jar

while i wanted to do that myself...

**Comment by draknyte1** [comment]
Don't support foreign builds of GT that don't conform.. you'll save yourself headaches

**Comment by Technus** [comment]
After talking with the boye who added them, they will be removed so i can claim the GTNH range for this (exacly the same blocks), assuming gtnh is not loaded (redundancy)
